# Generated by Django 5.1.3 on 2024-12-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_chat',
            name='member',
            field=models.CharField(max_length=100),
        ),
    ]
