# Generated by Django 5.1.3 on 2025-01-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0002_alter_group_chat_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='group_chat',
        ),
    ]
