# Generated by Django 5.1.3 on 2024-12-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mem_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mem_group',
        ),
    ]
